apiVersion: operators.coreos.com/v1alpha1
kind: ClusterServiceVersion
metadata:
  annotations:
    alm-examples: '[]'
    capabilities: Basic Install
  name: myoperator.v0.0.0
  namespace: placeholder
spec:
  apiservicedefinitions: {}
  customresourcedefinitions:
    owned:
    - description: MyResource is the Schema for the myresources API
      displayName: My Resource
      kind: MyResource
      name: myresources.mygroup.local.dev
      version: v1alpha1
  description: test
  displayName: test
  icon:
  - base64data: ""
    mediatype: ""
  install:
    spec:
      deployments: null
    strategy: ""
  installModes:
  - supported: false
    type: OwnNamespace
  - supported: false
    type: SingleNamespace
  - supported: false
    type: MultiNamespace
  - supported: true
    type: AllNamespaces
  keywords:
  - test-nginx-operator
  links:
  - name: Myoperator
    url: https://myoperator.domain
  maturity: alpha
  provider:
    name: test
  version: 0.0.0
