apiVersion: mygroup.local.dev/v1alpha1
kind: MyResource
metadata:
  name: myresource-sample
spec:
  # TODO(user): Add fields here
  size: 2
  image: nginx:1.7.9
  type: NodePort # ClusterIP
  ports:
    - port: 80
      targetPort: 80
      nodePort: 30002